import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { ReactNode } from "react"
import { cookies } from "next/headers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children, parallel
}: Readonly<{
  children: ReactNode
  parallel: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link href="/">Home</Link>
          <Link href="/fetch">Fetch</Link>
          <Link href="/fetch-cache">Fetch Cache</Link>
          <Link href="/unstable_cache">Unstable_Cache</Link>
        </header>
        <hr />
        <main>
          {children}
        </main>
        <div className="pt-8 p-4 ">
          <p className="text-lg">Parallel Route</p>
          <main>
            {parallel}
          </main>
        </div>
      </body>
    </html>
  )
}

// export const dynamic = "force-dynamic"